//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coles.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coles.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;release-count&quot;: 2,
        ///  &quot;release-offset&quot;: 0,
        ///  &quot;releases&quot;: [
        ///    {
        ///      &quot;asin&quot;: null,
        ///      &quot;disambiguation&quot;: &quot;&quot;,
        ///      &quot;title&quot;: &quot;Danse Macabre&quot;,
        ///      &quot;date&quot;: &quot;2015-02-11&quot;,
        ///      &quot;quality&quot;: &quot;normal&quot;,
        ///      &quot;cover-art-archive&quot;: {
        ///        &quot;darkened&quot;: false,
        ///        &quot;front&quot;: true,
        ///        &quot;back&quot;: false,
        ///        &quot;count&quot;: 1,
        ///        &quot;artwork&quot;: true
        ///      },
        ///      &quot;id&quot;: &quot;4dbce414-a563-49d5-8c90-4ac8216cc1aa&quot;,
        ///      &quot;release-events&quot;: [
        ///        {
        ///          &quot;date&quot;: &quot;2015-02-11&quot;,
        ///          &quot;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lookup_response {
            get {
                return ResourceManager.GetString("lookup_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;created&quot;: &quot;2021-07-22T00:40:47.519Z&quot;,
        ///  &quot;count&quot;: 3,
        ///  &quot;offset&quot;: 0,
        ///  &quot;artists&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;05da26e5-6ee9-4d5c-97b2-a596e23fbda7&quot;,
        ///      &quot;type&quot;: &quot;Person&quot;,
        ///      &quot;type-id&quot;: &quot;b6e035f4-3ce9-331c-97df-83397230b0df&quot;,
        ///      &quot;score&quot;: 41,
        ///      &quot;gender-id&quot;: &quot;36d3d30a-839d-3eda-8cb3-29be4384e4a9&quot;,
        ///      &quot;name&quot;: &quot;Tuatara&quot;,
        ///      &quot;sort-name&quot;: &quot;Tuatara&quot;,
        ///      &quot;gender&quot;: &quot;male&quot;,
        ///      &quot;country&quot;: &quot;BY&quot;,
        ///      &quot;area&quot;: {
        ///        &quot;id&quot;: &quot;660e3c48-b301-3c8c-9708-0f71d5d094d6&quot;,
        ///        &quot;type&quot;: &quot;Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
    }
}
